//package com.aplus.model;
//
//public enum ResidentialCleanType {
//	STANDARD_CLEANING, DEEP_CLEANING, MOVEINCLEAN, MOVE_OUT_CLEANING, CARPET_CLEANING, POST_RENOVATION_CLEAN_UP, DISINFECTANT_CLEANING
//}
